import qbittorrentapi
import requests
import json
import os
from data.config import config

movies_directory = config['radarr']['movies_directory']
movies_directory_remote = config['radarr']['movies_directory_remote']
radarr_base_url = config['radarr']['base_url']
radarr_api_key = config['radarr']['api_key']

# instantiate a Client using the appropriate WebUI configuration
conn_info = dict(
    host=config["client"]["host"],
    port=config["client"]["port"],
    username=config["client"]["username"],
    password=config["client"]["password"]
)
qbt_client = qbittorrentapi.Client(**conn_info)

# test the provided login credentials.
try:
    qbt_client.auth_log_in()
except qbittorrentapi.LoginFailed as e:
    print(e)

# retrieve all torrents
torrents = qbt_client.torrents_info()

# get all movies in radarr
response_movies = requests.get(f"{radarr_base_url}/api/v3/movie?apikey={radarr_api_key}")
response_movies_dict = json.loads(response_movies.text)

for movie_entry in response_movies_dict:
    movie_id = movie_entry['id']
    print(f"Movie id : {movie_id}")
    
    # get all history entries from movie
    response_history = requests.get(f"{radarr_base_url}/api/v3/history/movie?apikey={radarr_api_key}&movieId={movie_id}")
    response_history_dict = json.loads(response_history.text)
    
    for history_entry in response_history_dict:
        if 'data' in history_entry:
            torrent_info_hash = ""
            dropped_path = ""
            torrent_to_move = None
            # when the action is "grabbed" check by hash
            if 'torrentInfoHash' in history_entry['data']:
                torrent_info_hash = history_entry['data']['torrentInfoHash']
                    
            # when the action is a manual import check by path
            if 'droppedPath' in history_entry['data']:
                dropped_path = history_entry['data']['droppedPath']

            for torrent in torrents:
                if torrent.hash == torrent_info_hash:
                    torrent_to_move = torrent
                    break
                if torrent.content_path in dropped_path:
                    torrent_to_move = torrent
                    break
            
            if torrent_to_move is not None:
                # get the series folder name generated by radarr
                imported_path = movie_entry['folderName']
                folder_name = imported_path.split('/')[-1]
                
                # create folder with same name on movies downloads directory
                folder_path = f"{movies_directory}/{folder_name}"
                folder_path_remote = f"{movies_directory_remote}/{folder_name}"
                os.makedirs(folder_path, exist_ok=True)

                # move torrent to created folder
                try:
                    qbt_client.torrents_set_save_path(save_path=folder_path_remote, torrent_hashes=[torrent_to_move.hash])
                    qbt_client.torrents_set_download_path(download_path=folder_path_remote, torrent_hashes=[torrent_to_move.hash])
                    qbt_client.torrents_set_location(location=folder_path_remote, torrent_hashes=[torrent_to_move.hash])
                except Exception as e2:
                    print(e2)

# be sure to log out:
qbt_client.auth_log_out()